import React from 'react';

const ProjectReportTemplate = ({ text }) => {
  const processText = (rawText) => {
    if (!rawText) return <p style={{ color: '#ccc', textAlign: 'center', marginTop: '50px' }}>Document content will appear here...</p>;
    
    const lines = rawText.split('\n');
    let titleFound = false;

    return lines.map((line, index) => {
      const trimmed = line.trim();
      if (!trimmed) return <br key={index} />;
      
      // Assume first non-empty line is the report title if not found yet
      if (!titleFound && trimmed.length > 0 && trimmed.length < 100) {
        titleFound = true;
        return (
          <div key={index} style={styles.titleContainer}>
            <h1 style={styles.title}>{trimmed}</h1>
            <div style={styles.divider}></div>
          </div>
        );
      }
      
      // Heuristic for section headers (short lines, uppercase or ending in colon or number dot)
      if (
        trimmed.length < 60 && 
        (trimmed === trimmed.toUpperCase() || trimmed.endsWith(':') || /^\d+\./.test(trimmed))
      ) {
        return <h2 key={index} style={styles.sectionHeader}>{trimmed}</h2>;
      }
      
      return <p key={index} style={styles.paragraph}>{trimmed}</p>;
    });
  };

  return (
    <div style={styles.container}>
      {/* Cover Page logic can be complex, so we'll just format the text beautifully */}
      <div style={styles.page}>
        <div style={styles.header}>Project Report</div>
        <div style={styles.content}>
          {processText(text)}
        </div>
        <div style={styles.footer}>
          <span>Generated by Document Formatter</span>
        </div>
      </div>
    </div>
  );
};

const styles = {
  container: {
    fontFamily: '"Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
    backgroundColor: '#f5f5f5',
    minHeight: '100%',
  },
  page: {
    backgroundColor: 'white',
    padding: '60px 80px',
    maxWidth: '850px',
    margin: '0 auto',
    boxShadow: '0 0 10px rgba(0,0,0,0.1)',
    position: 'relative',
    minHeight: '1100px', // roughly letter size aspect
  },
  header: {
    position: 'absolute',
    top: '20px',
    right: '80px',
    fontSize: '10px',
    color: '#888',
    textTransform: 'uppercase',
    letterSpacing: '1px',
  },
  footer: {
    position: 'absolute',
    bottom: '30px',
    left: '80px',
    right: '80px',
    fontSize: '10px',
    color: '#888',
    borderTop: '1px solid #eee',
    paddingTop: '10px',
    textAlign: 'center',
  },
  content: {
    marginTop: '20px',
    color: '#333',
    lineHeight: '1.7',
    fontSize: '11pt',
  },
  titleContainer: {
    marginBottom: '40px',
    marginTop: '40px',
    textAlign: 'center',
  },
  title: {
    fontSize: '28px',
    color: '#1a365d',
    fontWeight: '700',
    marginBottom: '15px',
  },
  divider: {
    height: '4px',
    width: '60px',
    backgroundColor: '#3b82f6',
    margin: '0 auto',
  },
  sectionHeader: {
    fontSize: '18px',
    fontWeight: '600',
    color: '#2d3748',
    marginTop: '30px',
    marginBottom: '15px',
    borderBottom: '2px solid #edf2f7',
    paddingBottom: '5px',
  },
  paragraph: {
    marginBottom: '15px',
    textAlign: 'justify',
  }
};

export default ProjectReportTemplate;
